language: cpp

sudo: false
dist: xenial

compiler:
  - clang
  - gcc

before_script:
  - git submodule update --init --recursive

  # print out some version numbers
  - $CMAKE_CXX --version
  - cmake --version

  # configure
  - mkdir build
  - cd build
  - cmake ..

script:
  - make -j2 && ctest -V
  - ../bin/artic_tools -v
