sudo: required
language: generic
dist: bionic

jobs:
  include:
    - os: linux
      name: "linux-clang10"
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: "deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-10 main"
              key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
          packages:
            - clang-10
            - libstdc++-7-dev
            - libboost-all-dev
      env: ["CXX=clang++-10", "CC=clang-10"]

    - os: linux
      name: "linux-g++10"
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: "deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-10 main"
              key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
          packages:
            - g++-10
            - libstdc++-7-dev
            - libboost-all-dev
      env: ["CXX=g++-10", "CC=gcc-10"]

    - os: osx
      name: "osx"
      osx_image: xcode10
      env: ["CXX=clang++", "XCODE_VERSION=11.3.1"]

install:
  - git submodule update --init --recursive

script:
  - g++ --version
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=Debug ..
  - make -j2
  - ../bin/artic-tools_tests
  - ../bin/artic-tools -v
  - ../bin/artic-tools align_trim -h
  - ../bin/artic-tools get_scheme nipah
  - ../bin/artic-tools validate_scheme -h
  - ../bin/artic-tools check_vcf -h
