language: cpp
sudo: true
dist: bionic

matrix:
  include:
    - os: osx
      osx_image: xcode10.1
    - os: linux

before_script:
  - git submodule update --init --recursive
  - pushd extlib/htslib
  - autoheader && autoconf && sudo make && sudo make install
  - popd

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j2
  - ../bin/artic_tests
  - ../bin/artic_tools -v
