language: cpp
sudo: true
dist: bionic

compiler: gcc
os: linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

before_script:
  - export CC=gcc-7
  - export CXX=g++-7
  - git submodule update --init --recursive
  - pushd extlib/htslib
  - autoheader && autoconf && sudo make && sudo make install
  - popd

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j2
  - ../bin/artic_tests
  - ../bin/artic_tools -v
