sudo: required
language: generic
dist: bionic

jobs:
  include:
    - os: linux
      name: "linux-clang10"
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: "deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-10 main"
              key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
          packages:
            - clang-10
            - libstdc++-7-dev
      env: ["CXX=clang++-10", "CC=clang-10"]

    - os: linux
      name: "linux-g++10"
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: "deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-10 main"
              key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
          packages:
            - g++-10
            - libstdc++-7-dev
      env: ["CXX=g++-10", "CC=gcc-10"]

    - os: osx
      name: "osx"
      osx_image: xcode11.3
      env: ["CXX=clang++", "XCODE_VERSION=11.3.1"]

install:
  # get the submodules
  - git submodule update --init --recursive

  # install htslib
  - pushd extlib/htslib
  - autoheader && autoconf && sudo make && sudo make install
  - popd

script:
  - g++ --version
  - mkdir build
  - cd build
  - cmake -Dgtest_disable_pthreads=OFF ..
  - make -j2
  - ../bin/artic_tests
  - ../bin/artic_tools -v
