language: cpp

sudo: true
dist: bionic

compiler:
  - clang
  - gcc

before_script:
  - git submodule update --init --recursive
  - pushd extlib/htslib
  - autoheader && autoconf && sudo make && sudo make install
  - popd
  - mkdir build
  - cd build
  - cmake ..

script:
  - make -j2 && ctest -V
  - ../bin/artic_tools -v
