sudo: required
language: cpp
dist: bionic

jobs:
  include:
    - os: linux
      name: "linux-clang10"
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: "deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-10 main"
              key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
          packages:
            - clang-10
      env: MATRIX_EVAL="CC=clang-10 && CXX=clang++-10"
    - os: linux
      name: "linux-g++10"
      addons:
        apt:
          update: true
          sources:
            - ubuntu-toolchain-r-test
            - sourceline: "deb https://apt.llvm.org/xenial/ llvm-toolchain-xenial-10 main"
              key_url: "https://apt.llvm.org/llvm-snapshot.gpg.key"
          packages:
            - g++-10
      env: MATRIX_EVAL="CC=gcc-10 && CXX=g++-10"
    - os: osx
      name: "osx"
      osx_image: xcode11.4
      env: MATRIX_EVAL="CC=clang && CXX=clang++"

before_install:
  - eval "${MATRIX_EVAL}"
  - g++ --version
  - |
    if [[ "${TRAVIS_OS_NAME}" == "linux" ]]; then
      export TRAVIS_OS=Linux
    elif [[ "${TRAVIS_OS_NAME}" == "osx" ]]; then
      export TRAVIS_OS=Darwin

install:
  # get the submodules
  - git submodule update --init --recursive

  # install htslib
  - pushd extlib/htslib
  - autoheader && autoconf && sudo make && sudo make install
  - popd

script:
  - mkdir build
  - cd build
  - cmake ..
  - make -j2
  - ../bin/artic_tests
  - ../bin/artic_tools -v
