language: cpp

sudo: false
dist: xenial

matrix:
  include:
    # gcc 7.x, Debug with -O1
    - env: CMAKE_CC="gcc" CMAKE_CXX="g++" BUILD_TYPE="Debug" COMPILER_FLAGS="-O1"

    # gcc 7.x, Release
    - env: CMAKE_CC="gcc" CMAKE_CXX="g++" BUILD_TYPE="Release" COMPILER_FLAGS=""

before_script:
  # print out some version numbers
  - $CMAKE_CXX --version
  - cmake --version

  # configure
  - mkdir build; cd build
  - cmake
    -DCMAKE_BUILD_TYPE="$BUILD_TYPE"
    -DCMAKE_C_COMPILER="$CMAKE_CC" -DCMAKE_CXX_COMPILER="$CMAKE_CXX"
    -DCMAKE_C_FLAGS="$COMPILER_FLAGS" -DCMAKE_CXX_FLAGS="$COMPILER_FLAGS"
    $CMAKE_ARGS ..

script:
  - make -j2 && ctest -V
  - ../bin/artic_tools -v
