site_name: artic tools
repo_url: https://github.com/will-rowe/artic_tools
theme: readthedocs
nav:
  - Home: "index.md"
  - "User Guide":
      - "Installation": "installation.md"
      - "Quick Start": "quick-start.md"
      - "Commands": "commands.md"
  - About:
      - "Softmasker": "softmasker.md"
