site_name: artic-tools
repo_url: https://github.com/will-rowe/artic-tools
theme: readthedocs
nav:
        - Home: "index.md"
        - "User Guide":
                  - "Installation": "installation.md"
                  - "Commands": "commands.md"
        - About:
                  - "Primer Schemes": "primerscheme.md"
                  - "Softmasking": "softmasker.md"
