name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    name: ${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        toolchain:
          - linux-gcc
          - macos-clang
          - windows-msvc

        configuration:
          - debug

        include:
          - toolchain: linux-gcc
            os: ubuntu-latest
            compiler: gcc

          - toolchain: macos-clang
            os: macos-latest
            compiler: clang

          - toolchain: windows-msvc
            os: windows-latest
            compiler: msvc

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: install boost-curl linux
        run: sudo apt-get install libboost-all-dev libcurl4-openssl-dev -y
        if: matrix.os == 'ubuntu-latest'

      - name: install boost-curl osx
        run: brew install boost
        if: matrix.os == 'macos-latest'

      - name: install boost-curl windows
        if: matrix.os == 'windows-latest'
        uses: MarkusJx/install-boost@v1.0
        id: install-boost
        with:
          boost_version: 1.71.0
          toolset: msvc14.2

      - name: Configure (windows)
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.configuration }}
        if: matrix.os == 'windows-latest'
        env:
          BOOST_ROOT: ${{steps.install-boost.outputs.BOOST_ROOT}}

      - name: Configure (*nix)
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.configuration }}
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'

      - name: Build with ${{ matrix.compiler }}
        run: cmake --build build

      - name: Test
        working-directory: build
        env:
          CTEST_OUTPUT_ON_FAILURE: 1
        run: ctest -C ${{ matrix.configuration }}
