name: CI

on:
  push:
  pull_request:

jobs:
  build-and-test:
    name: ${{ matrix.toolchain }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        toolchain:
          - linux-gcc
          - macos-clang
          - windows-msvc

        configuration:
          - debug

        include:
          - toolchain: linux-gcc
            os: ubuntu-latest
            compiler: gcc

          - toolchain: macos-clang
            os: macos-latest
            compiler: clang

          - toolchain: windows-msvc
            os: windows-latest
            compiler: msvc

    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          submodules: true

      - name: install boost linux
        run: sudo apt-get install libboost-all-dev -y
        if: matrix.os == 'ubuntu-latest'

      - name: install boost osx
        run: brew install boost
        if: matrix.os == 'macos-clang'

      - name: install boost windows
        if: matrix.os == 'windows-msvc'
        uses: MarkusJx/install-boost@v1.0
        id: install-boost
        with:
          boost_version: 1.71.0
          toolset: msvc14.2

      - name: Configure (${{ matrix.configuration }})
        run: cmake -S . -B build -DCMAKE_BUILD_TYPE=${{ matrix.configuration }}

      - name: Build with ${{ matrix.compiler }}
        run: cmake --build build

      - name: Test
        working-directory: build
        env:
          CTEST_OUTPUT_ON_FAILURE: 1
        run: ctest -C ${{ matrix.configuration }}
